name = "gelyos-contact-worker"
main = "src/index.ts"
compatibility_date = "2024-11-07"

routes = [
  { pattern = "gelyos.fr/api/contact*", zone_id = "12f0aca7a17c7f2d5d700d93b5e97111" },
  { pattern = "www.gelyos.fr/api/contact*", zone_id = "12f0aca7a17c7f2d5d700d93b5e97111" } # optionnel si tu g√®res le www
]

# Definis ALLOWED_ORIGINS dans le dashboard si besoin (ex: "https://gelyos.fr,https://www.gelyos.fr")
